

# server port (needed for Render later)
server.port=${PORT:8080}

# database config
spring.datasource.url=jdbc:postgresql://db.keaufceszkpjaipmeqly.supabase.co:5432/postgres?user=postgres&password=myZoO6tBRJrSDeuy
spring.datasource.username=postgres
spring.datasource.password=myZoO6tBRJrSDeuy

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.base-url=http://localhost:8080